### ISSUE TITLE
e2e test breakages

### ISSUE THREAD

**Issue by govuklaurence** [datagovuk/publish_data_beta#193]
- [x] Create a dataset frequency tests (#190)
- [x] Modify dataset - "Change your dataset's details" (#196)
- [x] Confirm Delete on files and docs (#195)
- [x] Edit dataset title (#191)
- [ ] Admin can delete a published dataset (#197)
- [x] Unable to locate CSS Selectors (#194)

```
TEST FAILURE: 12 errors during execution,  16 assertions failed, 669 passed. (4m 56s)

✖ create

   - Create a dataset, omit frequency (10.47s)
Testing if element <h1> contains text: "There was a problem". - expected "There was a problem" but got: "How frequently is this dataset updated?"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_omit_frequency [as Create a dataset, omit frequency] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:177:6)

   - Create a dataset, frequency daily, omit link (9.756s)
   Testing if element <h1> contains text: "There was a problem".  - expected "There was a problem" but got: "Add a link to your data"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_daily_omit_link [as Create a dataset, frequency daily, omit link] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:198:6)

   - Create a dataset, frequency monthly (11.494s)
   Testing if element <h1> contains text: "Links to your data".  - expected "Links to your data" but got: "Add a link to your data"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_monthly [as Create a dataset, frequency monthly] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:279:6)

   - Create a dataset, monthly, bad month (12.714s)
   Testing if element <h1> contains text: "There was a problem".  - expected "There was a problem" but got: "Add a link to your data"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_monthly_bad_month [as Create a dataset, monthly, bad month] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:239:6)

   - Create a dataset, monthly, bad year (11.78s)
   Testing if element <h1> contains text: "There was a problem".  - expected "There was a problem" but got: "Add a link to your data"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_monthly_bad_year [as Create a dataset, monthly, bad year] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:255:6)

   - Create a dataset, yearly, bad year (9.009s)
   Testing if element <h1> contains text: "There was a problem".  - expected "There was a problem" but got: "Links to your data"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_yearly_bad_year [as Create a dataset, yearly, bad year] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:354:6)

   - Create a dataset, omit url (8.861s)
   Testing if element <h1> contains text: "There was a problem".  - expected "There was a problem" but got: "Add a link to your data"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_omit_url [as Create a dataset, omit url] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:371:6)

   - Create a dataset, modify title (10.138s)
   Testing if element <h1> contains text: "Change your dataset's details".  - expected "Change your dataset's details" but got: "Create a dataset"
       at Object.test_create_modify_title [as Create a dataset, modify title] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:382:13)
       at _combinedTickCallback (internal/process/next_tick.js:95:7)
       at process._tickCallback (internal/process/next_tick.js:161:9)

   - Create a dataset, modify licence (11.194s)
   Testing if element <h1> contains text: "Publish ‘TEST- some dataset’".  - expected "Publish ‘TEST- some dataset’" but got: "Choose a licence for this dataset"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.test_create_modify_licence [as Create a dataset, modify licence] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:395:6)

   - Create a dataset, remove link after check (10.077s)
   Testing if element <h1> contains text: "Are you sure you want to delete ‘TEST- some datafile’?".  - expected "Are you sure you want to delete ‘TEST- some datafile’?" but got: "Links to your data"
       at Object.browser.clickAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:36:15)
       at Object.test_create_remove_link [as Create a dataset, remove link after check] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:406:6)

   - Create a dataset, remove doc after check (10.288s)
   Testing if element <h1> contains text: "Are you sure you want to delete ‘TEST- some doc’?".  - expected "Are you sure you want to delete ‘TEST- some doc’?" but got: "Links to supporting documents"
       at Object.browser.clickAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:36:15)
       at Object.test_create_remove_doc [as Create a dataset, remove doc after check] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:423:6)

 ✖ edit

   - Edit a dataset title  (10.581s)
   Testing if element <h1> contains text: "Edit ‘TEST- some dataset’".  - expected "Edit ‘TEST- some dataset’" but got: "Publish ‘TEST- some dataset’"
       at Object.browser.clickAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:36:15)
       at Object.test_edit_title [as Edit a dataset title ] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/edit.js:50:6)

   - Edit a dataset location (10.252s)
   Testing if element <h1> contains text: "Edit ‘TEST- some dataset’".  - expected "Edit ‘TEST- some dataset’" but got: "Publish ‘TEST- some dataset’"
       at Object.browser.clickAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:36:15)
       at Object.test_edit_location [as Edit a dataset location] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/edit.js:61:6)

   - Cancel editing a dataset location (10.312s)
   Testing if element <h1> contains text: "Edit ‘TEST- some dataset’".  - expected "Edit ‘TEST- some dataset’" but got: "Publish ‘TEST- some dataset’"
       at Object.browser.clickAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:36:15)
       at Object.test_edit_location_cancel [as Cancel editing a dataset location] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/edit.js:86:6)

   - User cannot delete a published dataset (10.476s)
   Testing if element <h1> contains text: "Edit ‘TEST- some dataset’".  - expected "Edit ‘TEST- some dataset’" but got: "Publish ‘TEST- some dataset’"
       at Object.browser.clickAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:36:15)
       at Object.test_cant_delete_published [as User cannot delete a published dataset] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/edit.js:95:6)

   - Admin can delete a published dataset (5.339s)
   Testing if element <h1> contains text: "Tasks".  - expected "Tasks" but got: "There was a problem signing you in"
       at Object.browser.submitFormAndCheckNextTitle (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:30:15)
       at Object.login (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:66:6)
       at createDataset (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/edit.js:7:17)
       at Object.test_admin_can_delete_published [as Admin can delete a published dataset] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/edit.js:101:3)

   ERROR: Unable to locate element: "input[id=period_month]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:8)
       at Object.test_create_monthly [as Create a dataset, frequency monthly] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:277:6)


   ERROR: Unable to locate element: "input[id=period_month]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:29)
       at Object.test_create_monthly [as Create a dataset, frequency monthly] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:277:6)


   ERROR: Unable to locate element: "input[id=period_year]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:8)
       at Object.test_create_monthly [as Create a dataset, frequency monthly] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:278:6)


   ERROR: Unable to locate element: "input[id=period_year]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:29)
       at Object.test_create_monthly [as Create a dataset, frequency monthly] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:278:6)


   ERROR: Unable to locate element: "input[id=period_month]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:8)
       at Object.test_create_monthly_bad_month [as Create a dataset, monthly, bad month] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:237:6)


   ERROR: Unable to locate element: "input[id=period_month]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:29)
       at Object.test_create_monthly_bad_month [as Create a dataset, monthly, bad month] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:237:6)


   ERROR: Unable to locate element: "input[id=period_year]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:8)
       at Object.test_create_monthly_bad_month [as Create a dataset, monthly, bad month] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:238:6)


   ERROR: Unable to locate element: "input[id=period_year]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:29)
       at Object.test_create_monthly_bad_month [as Create a dataset, monthly, bad month] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:238:6)


   ERROR: Unable to locate element: "input[id=period_month]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:8)
       at Object.test_create_monthly_bad_year [as Create a dataset, monthly, bad year] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:253:6)


   ERROR: Unable to locate element: "input[id=period_month]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:29)
       at Object.test_create_monthly_bad_year [as Create a dataset, monthly, bad year] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:253:6)


   ERROR: Unable to locate element: "input[id=period_year]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:8)
       at Object.test_create_monthly_bad_year [as Create a dataset, monthly, bad year] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:254:6)


   ERROR: Unable to locate element: "input[id=period_year]" using: css selector
       at Object.browser.clearSetValue (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/common.js:48:29)
       at Object.test_create_monthly_bad_year [as Create a dataset, monthly, bad year] (/Users/laurencesmith/src/publish_data_beta/spec/end-to-end-tests/tests/create.js:254:6)



Stopping test server at 50639
Removing test database publish_beta_e2e_tests
```
